# Generated by Django 5.1.6 on 2025-03-06 15:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="is_reversed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="reversed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="reversed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="reversed_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="payment_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
