# Generated by Django 5.1.6 on 2025-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customer_order",
            "0002_orderpayment_is_reversed_orderpayment_reversed_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="paymode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("MFS", "MFS"),
                    ("BANK", "Bank Draft"),
                    ("RTGS", "RTGS"),
                    ("CHEQUE", "Cheque"),
                    ("BEFTN", "BEFTN"),
                ],
                default="CASH",
                max_length=255,
            ),
        ),
    ]
