# Generated by Django 5.1.7 on 2025-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0003_alter_orderpayment_paymode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderline",
            old_name="quantity",
            new_name="deliver_quantity",
        ),
        migrations.AddField(
            model_name="orderline",
            name="order_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RETURN", "Return"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("SHIPPED", "Shipped"),
                    ("DELIVERED", "Delivered"),
                    ("PARTIAL_DELIVERED", "Partial Delivered"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
