# Generated by Django 5.2.3 on 2025-07-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0005_orderdelivery_orderdeliverybill_orderdeliveryline"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="return_for_delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_deliveries",
                to="customer_order.orderdelivery",
            ),
        ),
    ]
