# Generated by Django 5.2.3 on 2025-07-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0006_orderdelivery_return_for_delivery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdelivery",
            name="quantity",
        ),
    ]
