# Generated by Django 5.2.3 on 2025-07-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0007_remove_orderdelivery_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdeliverybill",
            name="bill_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderdeliverybill",
            name="bill_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
