# Generated by Django 5.2.3 on 2025-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0008_alter_orderdeliverybill_bill_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="shipped_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderdelivery",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
