# Generated by Django 5.2.3 on 2025-07-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0009_orderdelivery_shipped_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdelivery",
            name="total_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
