# Generated by Django 5.2.3 on 2025-07-13 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0010_orderdelivery_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdelivery",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="customer_order.order",
            ),
        ),
    ]
