# Generated by Django 5.2.3 on 2025-07-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_order", "0011_alter_orderdelivery_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderdelivery",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="orderdeliveryline",
            unique_together=set(),
        ),
    ]
