# Generated by Django 5.1.3 on 2024-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='country',
            name='continent_code',
            field=models.CharField(max_length=2, verbose_name='Continent Code'),
        ),
    ]
