# Generated by Django 5.1.3 on 2025-01-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navmenu",
            options={
                "ordering": ["order"],
                "verbose_name": "Navigation Menu",
                "verbose_name_plural": "Navigation Menus",
            },
        ),
    ]
