# Generated by Django 5.1.1 on 2024-09-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Determines if the user is active or not', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions but not as same superuser.', verbose_name='Admin Status'),
        ),
    ]
