# Generated by Django 5.1.3 on 2024-12-15 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_remove_company_company_favico_and_more"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="allowed_products", to="company.company"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_product_brands",
                to="product.productbrand",
            ),
        ),
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details",
                to="product.product",
            ),
        ),
    ]
