# Generated by Django 5.1.3 on 2024-12-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_companies_alter_product_brand_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productbrand",
            options={"verbose_name": "Brand", "verbose_name_plural": "Product Brands"},
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_product_categories",
                to="product.productcategory",
            ),
        ),
    ]
