# Generated by Django 5.1.3 on 2024-12-15 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_initial"),
        ("product", "0003_alter_productbrand_options_and_more"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uom_purchase_products",
                to="uom.uom",
                verbose_name="Purchase UOM",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="country_products",
                to="country.country",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SKU"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="uom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uom_products",
                to="uom.uom",
                verbose_name="UOM",
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="country_product_brands",
                to="country.country",
            ),
        ),
    ]
