# Generated by Django 5.1.6 on 2025-03-07 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_remove_product_default_image_1_and_more"),
        ("sale_order", "0006_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="sale_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="sale_order.paikarsaleorder",
            ),
        ),
    ]
