# Generated by Django 5.1.7 on 2025-03-13 03:38

import core.storage_config.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_productimage_sale_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="category_image",
            field=models.ImageField(
                blank=True,
                help_text="Product Category Image",
                null=True,
                upload_to=core.storage_config.file_path.upload_product_category_image,
            ),
        ),
    ]
