# Generated by Django 5.1.7 on 2025-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_productcategory_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
