# Generated by Django 5.2.3 on 2025-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockInMovement",
            fields=[],
            options={
                "verbose_name": "In Stock Movement",
                "verbose_name_plural": "In Stock Movements",
                "ordering": ["-created_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stockmovement",),
        ),
        migrations.CreateModel(
            name="StockOutMovement",
            fields=[],
            options={
                "verbose_name": "Out Stock Movement",
                "verbose_name_plural": "Out Stock Movements",
                "ordering": ["-created_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stockmovement",),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ORDER", "Purchase Order"),
                    ("SALE_ORDER", "Sale Order"),
                    ("ADJUSTMENT", "Manual Adjustment"),
                    ("PURCHASE_RETURN", "Purchase Return"),
                ],
                max_length=50,
                verbose_name="Reference Type",
            ),
        ),
    ]
