# Generated by Django 5.1.3 on 2025-01-13 05:34

import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0006_alter_company_allowed_products"),
        ("product", "0007_alter_product_attributes_and_more"),
        ("uom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaikarSaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=255, unique=True)),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "product_grade",
                    models.CharField(blank=True, max_length=88, null=True),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "validity_dates",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        blank=True, null=True
                    ),
                ),
                ("has_vat", models.BooleanField(default=False)),
                (
                    "vat_ratio",
                    models.FloatField(
                        default=0.0, help_text="VAT ratio in percentage if has VAT"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected"),
                            ("delivered", "Delivered"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially Paid"),
                        ],
                        default="pending_approval",
                        max_length=50,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paikar_sale_order_approved_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paikar_sale_orders",
                        to="company.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paikar_sale_orders",
                        to="product.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale_order_paikar_sale_order",
            },
        ),
        migrations.CreateModel(
            name="PaikarSaleOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_slab",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(),
                ),
                ("rate", models.FloatField(default=0.0)),
                ("share_commission", models.FloatField(default=0.0)),
                ("others_charge", models.FloatField(default=0.0)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paikar_sale_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sale_order.paikarsaleorder",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="uom.uom"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale_order_paikar_sale_order_line",
            },
        ),
        migrations.CreateModel(
            name="SaleOrderSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prefix",
                    models.CharField(
                        choices=[
                            ("CSO", "Customer Sale Order"),
                            ("PSO", "Paikar Sale Order"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sequence_date", models.DateField(default=django.utils.timezone.now)),
                ("counter", models.IntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sale_order_sale_order_sequence",
                "unique_together": {("prefix", "sequence_date")},
            },
        ),
    ]
