# Generated by Django 5.1.3 on 2025-01-13 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paikarsaleorderline",
            name="paikar_sale_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderlines",
                to="sale_order.paikarsaleorder",
            ),
        ),
    ]
