# Generated by Django 5.1.3 on 2025-02-03 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0002_alter_paikarsaleorderline_paikar_sale_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikarsaleorder",
            name="approved_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
