# Generated by Django 5.1.3 on 2025-02-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0003_paikarsaleorder_approved_on"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paikarsaleorder",
            options={
                "verbose_name": "Paikar Sale Order",
                "verbose_name_plural": "Paikar Sale Orders",
            },
        ),
        migrations.RemoveField(
            model_name="paikarsaleorder",
            name="company_name",
        ),
    ]
