# Generated by Django 5.1.7 on 2025-03-19 15:15

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_remove_company_company_favicon_and_more"),
        ("product", "0010_productcategory_slug_and_more"),
        ("sale_order", "0006_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paikarsaleorder",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["validity_dates"], name="sale_order__validit_cfb200_gist"
            ),
        ),
    ]
