# Generated by Django 5.1.7 on 2025-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0007_paikarsaleorder_sale_order__validit_cfb200_gist"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikarsaleorderline",
            name="discount_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="paikarsaleorderline",
            name="margin_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
