# Generated by Django 5.1.7 on 2025-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0008_paikarsaleorderline_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikarsaleorderline",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed")],
                default="percentage",
                max_length=50,
            ),
        ),
    ]
