# Generated by Django 5.2.3 on 2025-07-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_order", "0009_paikarsaleorderline_discount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paikarsaleorderline",
            name="customer_rate",
            field=models.FloatField(default=0.0),
        ),
    ]
