# Generated by Django 5.2.3 on 2025-08-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="entry_type",
            field=models.CharField(
                default="PO", max_length=255, verbose_name="Entry Type"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="remarks",
            field=models.TextField(blank=True, null=True, verbose_name="Remarks"),
        ),
    ]
