# Generated by Django 5.1.3 on 2025-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("google", "Google"),
                    ("email", "Email"),
                ],
                default="email",
                max_length=120,
            ),
        ),
    ]
