# Generated by Django 5.1.3 on 2024-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant_logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
