# Generated by Django 5.1.7 on 2025-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_auth_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("google", "Google"),
                    ("email", "Email"),
                    ("user_name", "Username"),
                ],
                default="email",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
