# Generated by Django 5.1.3 on 2024-12-04 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('user', '0002_alter_user_created_by_alter_user_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bin_id',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_address_users', to='address.address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_address_users', to='address.address'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/logo/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tin_id',
            field=models.CharField(blank=True, max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('central_admin', 'Central Admin'), ('wholeseller', 'Wholeseller'), ('customer', 'Customer')], default='customer', max_length=55),
        ),
    ]
