# Generated by Django 5.1.7 on 2025-03-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_userprofile_phone_user_otp_code_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                default="<function now at 0x105069620>", max_length=88, unique=True
            ),
        ),
    ]
