# Generated by Django 5.1.3 on 2024-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('central_admin', 'Central Admin'), ('wholeseller_admin', 'Wholeseller Admin'), ('customer', 'Customer')], default='customer', max_length=55),
        ),
    ]
