# Generated by Django 5.1.7 on 2025-03-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_user_email_alter_user_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(max_length=88, unique=True),
        ),
    ]
