# Generated by Django 5.1.3 on 2025-02-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True, unique=True
            ),
        ),
    ]
