# Generated by Django 5.1.7 on 2025-03-12 04:08

import core.storage_config.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage_config.file_path.upload_blog_image,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="list_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage_config.file_path.upload_blog_image,
            ),
        ),
    ]
