# Generated by Django 5.1.3 on 2024-12-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='addr_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='addr_2',
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
