# Generated by Django 5.1.3 on 2024-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_favico",
        ),
        migrations.AddField(
            model_name="company",
            name="company_favicon",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/company/favicon"
            ),
        ),
    ]
