# Generated by Django 5.1.3 on 2024-12-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_company_allowed_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="theme_color",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
