# Generated by Django 5.1.3 on 2024-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_alter_company_theme_color"),
        ("product", "0005_remove_product_companies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="allowed_products",
            field=models.ManyToManyField(
                blank=True, related_name="companies", to="product.product"
            ),
        ),
    ]
