# Generated by Django 5.1.7 on 2025-03-08 07:14

import core.storage_config.file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_company_rating_companycategory_company_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_favicon",
        ),
        migrations.AddField(
            model_name="company",
            name="company_banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage_config.file_path.upload_company_image,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.storage_config.file_path.upload_company_image,
            ),
        ),
    ]
