# Generated by Django 5.1.3 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sub District',
                'verbose_name_plural': 'Sub Districts',
                'db_table': 'sub_district_sub_district',
                'ordering': ('name',),
            },
        ),
    ]
