# Generated by Django 5.1.3 on 2024-12-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('country', '0002_alter_country_options_alter_country_continent_code'),
        ('district', '0001_initial'),
        ('division', '0001_initial'),
        ('sub_district', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='content_type',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_countries', to='country.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_districts', to='district.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='address_divisions', to='division.division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_sub_districts', to='sub_district.subdistrict'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['content_type', 'object_id'], name='address_add_content_c8c3a6_idx'),
        ),
    ]
