# Generated by Django 5.1.3 on 2024-12-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_initial'),
        ('district', '0001_initial'),
        ('division', '0001_initial'),
        ('sub_district', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_districts', to='district.district'),
        ),
        migrations.AddField(
            model_name='address',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_divisions', to='division.division'),
        ),
        migrations.AddField(
            model_name='address',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_sub_districts', to='sub_district.subdistrict'),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['content_type', 'object_id'], name='address_add_content_c8c3a6_idx'),
        ),
    ]
