# Generated by Django 5.1.3 on 2024-12-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('default', 'Default'), ('delivery', 'Delivery'), ('contact', 'Contact'), ('general', 'General')], default='general', max_length=80),
        ),
    ]
