# Generated by Django 5.1.7 on 2025-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
