# Generated by Django 5.1.7 on 2025-05-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_address_is_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("default", "Default Address"),
                    ("delivery", "Delivery Address"),
                    ("contact", "Contact Address"),
                    ("general", "General Address"),
                    ("shipping", "Shipping Address"),
                    ("billing", "Billing Address"),
                ],
                default="general",
                max_length=80,
            ),
        ),
    ]
