# Generated by Django 5.1.3 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.JSONField(blank=True, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
                'db_table': 'action_action',
            },
        ),
    ]
