# Generated by Django 5.1.3 on 2024-12-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bn_name', models.CharField(max_length=255)),
                ('lat', models.CharField(blank=True, max_length=20, null=True)),
                ('long', models.FloatField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
                'db_table': 'district_district',
                'ordering': ('name',),
            },
        ),
    ]
