# Generated by Django 5.1.3 on 2024-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("district", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="long",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
