# Generated by Django 5.1.6 on 2025-03-07 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0004_rename_commission_mode_offer_comission_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cupon",
            name="valid_till",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="till when the cupon is valid",
            ),
            preserve_default=False,
        ),
    ]
