name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: ${{ vars.TARGET_DIR }}
          reverse: true
          parallel: 10
          ignoreFile: '.lftp_ignore'
          options: '--verbose'

      - name: Django Collect Static & Migrate
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd ${{ vars.TARGET_DIR }}
            source .venv/bin/activate
            uv sync
            python manage.py collectstatic --noinput
            python manage.py migrate
            sudo systemctl restart backend.aarothbd.com.service
            deactivate
