name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          # lftp settings
          onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: ${{ vars.TARGET_DIR }}
          reverse: true
          parallel: 10
          ignoreFile: '.lftp_ignore'
          options: '--verbose'

      - name: Django Collect Static & Migrate
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$KEY" > private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST
            # Navigate to your project directory
            cd ${{ vars.TARGET_DIR }}

            # Activate the virtual environment (update the path as needed)
            source .venv/bin/activate

            # Run Django-specific commands
            python manage.py collectstatic --noinput
            python manage.py migrate

            # Optional: Restart services (e.g., Gunicorn)
            sudo systemctl restart backend.aarothbd.com.service

            # Clean up
            deactivate
          EOF
          rm private_key
