name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup LFTP
        run:  sudo apt-get update && sudo apt-get install -y lftp

      - name: Run Deployment
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh ${{ secrets.FTP_HOST }} ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }} ./ ${{ secrets.FTP_TARGET_DIR }}
